# ETL completo — TechStore

## Objetivo

Neste notebook vamos construir o processo ETL antes de separar o código em arquivos:

1. **Extração**
   - Produtos e categorias da base PostgreSQL `TechStore`.
   - Dados de fornecedores do arquivo CSV.
2. **Transformação**
   - Padronização dos nomes das colunas.
   - Conversão de tipos.
   - Tratamento de dados ausentes e duplicados.
   - Integração das duas fontes.
   - Cálculo de margem e indicadores.
3. **Carga**
   - Tabela `techstore_etl.raw_fornecedores`.
   - Tabela `techstore_etl.processed_produtos`.
   - Tabela `techstore_etl.estatisticas_produtos`.
   - Arquivo Excel em `data/processed`.

## Antes de começar

Execute no terminal, na raiz do projeto:

```bash
python gerar_csv_fornecedores.py
```

Depois, configure o arquivo `.env`:

```env
DATABASE_URL=postgresql+psycopg2://postgres:SUA_SENHA@localhost:5432/techstore
```

Instale as dependências:

```bash
pip install pandas sqlalchemy psycopg2-binary python-dotenv openpyxl matplotlib jupyter
```

In [1]:
from sqlalchemy import create_engine, text
import pandas as pd
import requests

# Conexão com o ERP
engine_techstore = create_engine(
    "postgresql+psycopg2://postgres:postgres@localhost:5432/techstore"
)

# Conexão com o DW
engine_etl = create_engine(
    "postgresql+psycopg2://postgres:postgres@localhost:5432/techstore_etl"
)

print("Conexões configuradas.")

Conexões configuradas.

## 1. Extração da base TechStore

In [2]:
query_produtos = '''
    SELECT
        p.id_produto,
        p.nome AS produto,
        c.nome AS categoria,
        p.preco AS preco_venda
    FROM produtos p
    LEFT JOIN categorias c
        ON p.id_categoria = c.id_categoria
    ORDER BY p.id_produto;
'''

df_produtos_raw = pd.read_sql(text(query_produtos), con=engine_techstore)
df_produtos_raw.head()

   id_produto                  produto    categoria  preco_venda
0           1  Notebook Lenovo IdeaPad    Notebooks       3299.9
1           2   Notebook Dell Inspiron    Notebooks       4599.9
2           3           MacBook Air M2    Notebooks       7999.9
3           4                iPhone 15  Smartphones       4999.0
4           5               Galaxy S24  Smartphones       3999.0

In [3]:
df_produtos_raw.to_sql(
    "raw_produtos",
    con=engine_etl,
    schema="public",
    if_exists="replace",
    index=False
)

print("Tabela public.raw_produtos gravada no banco techstore_etl.")
df_produtos_raw.head()

Tabela public.raw_produtos gravada no banco techstore_etl.

   id_produto                  produto    categoria  preco_venda
0           1  Notebook Lenovo IdeaPad    Notebooks       3299.9
1           2   Notebook Dell Inspiron    Notebooks       4599.9
2           3           MacBook Air M2    Notebooks       7999.9
3           4                iPhone 15  Smartphones       4999.0
4           5               Galaxy S24  Smartphones       3999.0

## 2. Extração do CSV de fornecedores

In [4]:
RAW_DIR = "data/raw"

caminho_csv = f"{RAW_DIR}/techstore_fornecedores.csv"

df_fornecedores_raw = pd.read_csv(
    caminho_csv,
    sep=";",
    encoding="utf-8-sig"
)

df_fornecedores_raw.head()

,id_produto,produto,fornecedor,data_atualizacao,custo_aquisicao,prazo_entrega_dias,quantidade_reposicao,status_fornecimento
0,1,Notebook Lenovo IdeaPad,TechDistribuidora,2026-09-15,2450.0,7,10,Disponível
1,2,Notebook Dell Inspiron,TechDistribuidora,2026-09-15,3480.0,8,8,Disponível
2,3,MacBook Air M2,IMPORTADORA DIGITAL,2026-09-15,6250.0,15,5,Disponível
3,4,iPhone 15,Mobile SUPPLY,2026-09-16,3820.0,10,12,Disponível
4,5,Galaxy S24,Mobile Supply,2026-09-16,3010.0,12,20,Disponível

In [5]:
print("Produtos TechStore:", df_produtos_raw.shape)
print("Fornecedores CSV:", df_fornecedores_raw.shape)

display(df_produtos_raw.info())
display(df_fornecedores_raw.info())

Produtos TechStore: (14, 4)
Fornecedores CSV: (14, 8)
<class 'pandas.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id_produto   14 non-null     int64
 1   produto      14 non-null     str
 2   categoria    14 non-null     str
 3   preco_venda  14 non-null     float64
dtypes: float64(1), int64(1), str(2)
memory usage: 580.0 bytes

None

<class 'pandas.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id_produto            14 non-null     int64
 1   produto               14 non-null     str
 2   fornecedor            14 non-null     str
 3   data_atualizacao      14 non-null     str
 4   custo_aquisicao       14 non-null     float64
 5   prazo_entrega_dias    14 non-null     int64
 6   quantidade_reposicao  14 non-null     int64
 7   status_fornecimento   14 non-null     str
dtypes: float64(1), int64(3), str(4)
memory usage: 1.0 KB

None

In [6]:
df_fornecedores_raw.to_sql(
    "raw_fornecedores",
    con=engine_etl,
    schema="public",
    if_exists="replace",
    index=False
)

print("Dados gravados em public.raw_fornecedores.")
df_fornecedores_raw.head()

Dados gravados em public.raw_fornecedores.

,id_produto,produto,fornecedor,data_atualizacao,custo_aquisicao,prazo_entrega_dias,quantidade_reposicao,status_fornecimento
0,1,Notebook Lenovo IdeaPad,TechDistribuidora,2026-09-15,2450.0,7,10,Disponível
1,2,Notebook Dell Inspiron,TechDistribuidora,2026-09-15,3480.0,8,8,Disponível
2,3,MacBook Air M2,IMPORTADORA DIGITAL,2026-09-15,6250.0,15,5,Disponível
3,4,iPhone 15,Mobile SUPPLY,2026-09-16,3820.0,10,12,Disponível
4,5,Galaxy S24,Mobile Supply,2026-09-16,3010.0,12,20,Disponível

## 3. Tratamento dos dados de fornecedores

In [7]:
# Leitura das tabelas da camada raw no banco techstore_etl
df_produtos = pd.read_sql(
    "SELECT * FROM public.raw_produtos ORDER BY id_produto",
    con=engine_etl
)

df_fornecedores = pd.read_sql(
    "SELECT * FROM public.raw_fornecedores ORDER BY id_produto",
    con=engine_etl
)

print("Dados raw carregados para transformação.")
print("Produtos:", df_produtos.shape)
print("Fornecedores:", df_fornecedores.shape)

display(df_produtos.head())
display(df_fornecedores.head())

Dados raw carregados para transformação.
Produtos: (14, 4)
Fornecedores: (14, 8)

   id_produto                  produto    categoria  preco_venda
0           1  Notebook Lenovo IdeaPad    Notebooks       3299.9
1           2   Notebook Dell Inspiron    Notebooks       4599.9
2           3           MacBook Air M2    Notebooks       7999.9
3           4                iPhone 15  Smartphones       4999.0
4           5               Galaxy S24  Smartphones       3999.0

,id_produto,produto,fornecedor,data_atualizacao,custo_aquisicao,prazo_entrega_dias,quantidade_reposicao,status_fornecimento
0,1,Notebook Lenovo IdeaPad,TechDistribuidora,2026-09-15,2450.0,7,10,Disponível
1,2,Notebook Dell Inspiron,TechDistribuidora,2026-09-15,3480.0,8,8,Disponível
2,3,MacBook Air M2,IMPORTADORA DIGITAL,2026-09-15,6250.0,15,5,Disponível
3,4,iPhone 15,Mobile SUPPLY,2026-09-16,3820.0,10,12,Disponível
4,5,Galaxy S24,Mobile Supply,2026-09-16,3010.0,12,20,Disponível

In [ ]:
df_fornecedores_tratados = df_fornecedores.copy()

df_fornecedores_tratados.columns = (
    df_fornecedores_tratados.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

df_fornecedores_tratados["produto"] = (
    df_fornecedores_tratados["produto"]
    .astype("string")
    .str.strip()
)

df_fornecedores_tratados["fornecedor"] = (
    df_fornecedores_tratados["fornecedor"]
    .astype("string")
    .str.strip()
    .str.title()
)

df_fornecedores_tratados["status_fornecimento"] = (
    df_fornecedores_tratados["status_fornecimento"]
    .astype("string")
    .str.strip()
)

df_fornecedores_tratados["data_atualizacao"] = pd.to_datetime(
    df_fornecedores_tratados["data_atualizacao"]
)

colunas_numericas = [
    "id_produto",
    "custo_aquisicao",
    "prazo_entrega_dias",
    "quantidade_reposicao",
]

for coluna in colunas_numericas:
    df_fornecedores_tratados[coluna] = pd.to_numeric(
        df_fornecedores_tratados[coluna]
    )

df_fornecedores_tratados.head()

,id_produto,produto,fornecedor,data_atualizacao,custo_aquisicao,prazo_entrega_dias,quantidade_reposicao,status_fornecimento
0,1,Notebook Lenovo IdeaPad,Techdistribuidora,2026-09-15,2450.0,7,10,Disponível
1,2,Notebook Dell Inspiron,Techdistribuidora,2026-09-15,3480.0,8,8,Disponível
2,3,MacBook Air M2,Importadora Digital,2026-09-15,6250.0,15,5,Disponível
3,4,iPhone 15,Mobile Supply,2026-09-16,3820.0,10,12,Disponível
4,5,Galaxy S24,Mobile Supply,2026-09-16,3010.0,12,20,Disponível

## 4. Integração das fontes

In [ ]:
df_produtos_processados = df_produtos.merge(
    df_fornecedores_tratados,
    on=["id_produto", "produto"],
    how="left"
)

df_produtos_processados["margem_valor"] = (
    df_produtos_processados["preco_venda"]
    - df_produtos_processados["custo_aquisicao"]
)

df_produtos_processados["margem_percentual"] = (
    df_produtos_processados["margem_valor"]
    / df_produtos_processados["preco_venda"]
    * 100
).round(2)

df_produtos_processados.head()

,id_produto,produto,categoria,preco_venda,fornecedor,data_atualizacao,custo_aquisicao,prazo_entrega_dias,quantidade_reposicao,status_fornecimento,margem_valor,margem_percentual
0,1,Notebook Lenovo IdeaPad,Notebooks,3299.9,Techdistribuidora,2026-09-15,2450.0,7,10,Disponível,849.9,25.76
1,2,Notebook Dell Inspiron,Notebooks,4599.9,Techdistribuidora,2026-09-15,3480.0,8,8,Disponível,1119.9,24.35
2,3,MacBook Air M2,Notebooks,7999.9,Importadora Digital,2026-09-15,6250.0,15,5,Disponível,1749.9,21.87
3,4,iPhone 15,Smartphones,4999.0,Mobile Supply,2026-09-16,3820.0,10,12,Disponível,1179.0,23.58
4,5,Galaxy S24,Smartphones,3999.0,Mobile Supply,2026-09-16,3010.0,12,20,Disponível,989.0,24.73

In [10]:
df_produtos_processados.info()

<class 'pandas.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id_produto            14 non-null     int64
 1   produto               14 non-null     object
 2   categoria             14 non-null     str
 3   preco_venda           14 non-null     float64
 4   fornecedor            14 non-null     string
 5   data_atualizacao      14 non-null     datetime64[us]
 6   custo_aquisicao       14 non-null     float64
 7   prazo_entrega_dias    14 non-null     int64
 8   quantidade_reposicao  14 non-null     int64
 9   status_fornecimento   14 non-null     string
 10  margem_valor          14 non-null     float64
 11  margem_percentual     14 non-null     float64
dtypes: datetime64[us](1), float64(4), int64(3), object(1), str(1), string(2)
memory usage: 1.4+ KB

## 5. Geração das estatísticas

In [11]:
df_estatisticas = pd.DataFrame({
    "indicador": [
        "quantidade_produtos",
        "preco_medio",
        "custo_medio",
        "margem_media",
        "estoque_reposicao_total",
        "prazo_entrega_medio",
    ],
    "valor": [
        df_produtos_processados["id_produto"].nunique(),
        df_produtos_processados["preco_venda"].mean(),
        df_produtos_processados["custo_aquisicao"].mean(),
        df_produtos_processados["margem_percentual"].mean(),
        df_produtos_processados["quantidade_reposicao"].sum(),
        df_produtos_processados["prazo_entrega_dias"].mean(),
    ],
})

df_estatisticas

                 indicador        valor
0      quantidade_produtos    14.000000
1              preco_medio  2251.200000
2              custo_medio  1684.428571
3             margem_media    32.174286
4  estoque_reposicao_total   230.000000
5      prazo_entrega_medio     8.142857

## 6. Carga no PostgreSQL

In [13]:
df_produtos_processados.to_sql(
    "processed_produtos",
    con=engine_etl,
    schema="public",
    if_exists="replace",
    index=False
)

df_estatisticas.to_sql(
    "estatisticas_produtos",
    con=engine_etl,
    schema="public",
    if_exists="replace",
    index=False
)

print("Tabelas carregadas no PostgreSQL.")

Tabelas carregadas no PostgreSQL.

## 7. Exportação para Excel — camada processed

In [ ]:
PROCESSED_DIR = "data/processed"

caminho_excel = f"{PROCESSED_DIR}/relatorio_produtos.xlsx"

df_produtos_processados.to_excel(
    caminho_excel,
    index=False,
    engine="openpyxl"
)

Excel gerado: data/processed/relatorio_produtos.xlsx

## 8. Validação do resultado

In [18]:
consulta_validacao = '''
    SELECT *
    FROM public.processed_produtos
    ORDER BY id_produto
    LIMIT 10;
'''

pd.read_sql(text(consulta_validacao), con=engine_etl)

,id_produto,produto,categoria,preco_venda,fornecedor,data_atualizacao,custo_aquisicao,prazo_entrega_dias,quantidade_reposicao,status_fornecimento,margem_valor,margem_percentual
0,1,Notebook Lenovo IdeaPad,Notebooks,3299.9,Techdistribuidora,2026-09-15,2450.0,7,10,Disponível,849.9,25.76
1,2,Notebook Dell Inspiron,Notebooks,4599.9,Techdistribuidora,2026-09-15,3480.0,8,8,Disponível,1119.9,24.35
2,3,MacBook Air M2,Notebooks,7999.9,Importadora Digital,2026-09-15,6250.0,15,5,Disponível,1749.9,21.87
3,4,iPhone 15,Smartphones,4999.0,Mobile Supply,2026-09-16,3820.0,10,12,Disponível,1179.0,23.58
4,5,Galaxy S24,Smartphones,3999.0,Mobile Supply,2026-09-16,3010.0,12,20,Disponível,989.0,24.73
5,6,Motorola Edge 50,Smartphones,2499.9,Mobile Supply,2026-09-16,1880.0,9,15,Disponível,619.9,24.80
6,7,Mouse Logitech MX,Periféricos,399.9,Periféricos Brasil,2026-09-17,245.0,5,35,Disponível,154.9,38.73
7,8,Teclado Mecânico Redragon,Periféricos,289.9,Periféricos Brasil,2026-09-17,175.0,6,25,Disponível,114.9,39.63
8,9,Headset HyperX,Periféricos,349.9,Periféricos Brasil,2026-09-17,215.0,7,18,Disponível,134.9,38.55
9,10,"Monitor LG 24""",Monitores,899.9,Techdistribuidora,2026-09-18,610.0,9,10,Disponível,289.9,32.21

## Conclusão

O notebook executou o fluxo completo:

- **Extract:** PostgreSQL + CSV.
- **Transform:** limpeza, conversão, integração e cálculos.
- **Load:** PostgreSQL + Excel.

Na próxima etapa, o mesmo fluxo foi separado nos arquivos:

- `src/extract.py`
- `src/transform.py`
- `src/load.py`
- `src/run_etl.py`

Execute a versão modular pela raiz do projeto:

```bash
python -m src.run_etl
```